export const mockStations = [
  {
    id: 1,
    name: 'Downtown Charge Hub',
    address: '123 Main St',
    lat: 40.7128,
    lng: -74.006,
    pricePerKwh: 0.32,
    availablePorts: 3,
    totalPorts: 6,
    connectorTypes: ['Type2', 'CCS'],
  },
  {
    id: 2,
    name: 'Riverside EV Station',
    address: '45 River Rd',
    lat: 40.7228,
    lng: -74.0,
    pricePerKwh: 0.29,
    availablePorts: 1,
    totalPorts: 4,
    connectorTypes: ['CCS'],
  },
  {
    id: 3,
    name: 'Uptown Power Point',
    address: '789 North Ave',
    lat: 40.72,
    lng: -73.995,
    pricePerKwh: 0.35,
    availablePorts: 5,
    totalPorts: 8,
    connectorTypes: ['Type2', 'CHAdeMO'],
  },
  {
    id: 4,
    name: 'Westside Fast Charge',
    address: '22 West Blvd',
    lat: 40.71,
    lng: -74.015,
    pricePerKwh: 0.4,
    availablePorts: 0,
    totalPorts: 2,
    connectorTypes: ['CCS'],
  },
];
